### PR TITLE
Add back export of keys

### LINKED ISSUE #3106: Bug: getSimplePathPlans() fails with TypeError
### Description

After upgrading from 4.30.2 to 4.30.3 `model.getSimplePathPlans()` emits `TypeError`.

### Expected result

Should run as 4.30.2

### Actual result

```
TypeError: (0 , utils_1.keys) is not a function
    at getSimplePaths (/builds/platynum/certification-authority/flows/node_modules/@xstate/graph/lib/graph.js:316:49)
    at TestModel.getSimplePathPlans (/builds/platynum/certification-authority/flows/node_modules/@xstate/test/lib/index.js:157:54)
    at Suite.<anonymous> (/builds/platynum/certification-authority/flows/test/ca-acme.js:989:51)
[...]
```

### Reproduction

https://gitlab.com/platynum/certification-authority/flows/-/blob/master/test/ca-acme.js#L989

### Additional context

[Code that triggers this issue](https://gitlab.com/platynum/certification-authority/flows/-/blob/master/test/ca-acme.js#L989) and [full output](https://gitlab.com/platynum/certification-authority/flows/-/jobs/2156264224#L62) of mocha

### PR DESCRIPTION
**Pull request by davidkpiano**
Fixes #3106

The reason that the removal of `keys()` broke the above issue is because various XState tools depend on the `keys()` function to be exported from XState, but it was removed in the newest version.

### CODE REVIEW

**Review by calvinchengx — APPROVED** [review]

File: .changeset/kind-waves-provide.md [hunk 1]
```diff
@@ -0,0 +1,5 @@
+---
+'xstate': patch
+---
+
+The `keys()` utility function export, which was removed in #3089, is now added back, as older versions of XState libraries may depend on it still. See #3106 for more details.
```
Comment (Andarist) [inline .changeset/kind-waves-provide.md:5]:
```suggestion
The `keys()` utility function export, which was removed in [#3089](https://github.com/statelyai/xstate/issues/3089), is now added back, as older versions of XState libraries may depend on it still. See [#3106](https://github.com/statelyai/xstate/issues/3106) for more details.
```
