### ISSUE TITLE
Property 'observable' does not exist on type 'SymbolConstructor'. (Updating from 4.27.0 to 4.28.0)

### ISSUE THREAD

**Issue by Greg-Hitchon** [statelyai/xstate#2950]
**Description**
After updating to 4.28.0 I get the error:

`Property 'observable' does not exist on type 'SymbolConstructor'.` for a number of xstate type defs:

![image](https://user-images.githubusercontent.com/3837138/150002334-57068f93-f9af-4b06-8092-e2c683fd2b9b.png)

**Expected Result**
No errors

**Additional context**
It seems that #2835 removed a declaration:
![image](https://user-images.githubusercontent.com/3837138/150002572-4d478627-30c9-4a4f-a54e-409b3a3ff4fd.png)

Not sure if there is some expected config/settings that should be added, however it is unclear and seems to be a breaking change (at least for me) which was unexpected.

**Comment by umerkk** [comment]
+1. it is a breaking change for us.

**Comment by Andarist** [comment]
Sorry for the inconvenience. I'm investigating the issue and we should have a fix out for this tomorrow.

**Comment by davidkpiano** [comment]
cc. @woutermont 

The change is here, for reference: https://github.com/statelyai/xstate/pull/2835

**Comment by Andarist** [comment]
You should be able to work around this by using [`skipLibCheck`](https://www.typescriptlang.org/tsconfig#skipLibCheck) (this is a recommended thing to do either way since it can improve your TS startup times etc)

**Comment by woutermont** [comment]
Ahh, could have known... Removed the necessary declaration because of a comment, since it did not seek to matter anymore (https://github.com/statelyai/xstate/pull/2835#discussion_r765040293_) ... apparently it does. Restoring it should fix that.

**Comment by umerkk** [comment]
Do we have any ETA for a new patch release?
