### ISSUE TITLE
@xstate/test

### ISSUE THREAD

**Issue by calvinchengx** [statelyai/xstate#3115]
### Description

For `@xstate/test` both v2.0.0 and v2.0.1, this still happens for `xstate` v4.30.4

If I revert back to `@xstate/test` v2.0.0 and `xstate` v4.30.2, the test fails and complains that `getSimplePathPlans()` has a type error.

```bash
  ● Test suite failed to run


    TypeError: (0 , utils_1.keys) is not a function

      60 |   })
      61 |
    > 62 |   const testPlans = betaModel.getSimplePathPlans()
         |                               ^
      63 |
      64 |   testPlans.forEach((plan) => {
      65 |     describe(plan.description, () => {

      at getSimplePaths (node_modules/@xstate/graph/lib/graph.js:316:49)
      at TestModel.getSimplePathPlans (node_modules/@xstate/test/lib/index.js:157:54)
  ```

### Expected result

Works for v2.0.0 and v4.30.2.

I am expecting this to still work after upgrading to v2.0.1 (@xstate/test) and v4.30.4 (xstate)

### Actual result

```bash
Test suite failed to run

    TypeError: (0 , utils_1.keys) is not a function
```

### Reproduction

NA

**Comment by mattpocock** [comment]
@calvinchengx Should be fixed in 4.30.3

**Comment by Andarist** [comment]
@mattpocock this issue is specifically about this not being fixed by the latest release

**Comment by mattpocock** [comment]
@Andarist Whoops
