### ISSUE TITLE
Bug: Node.js types are included in 4.29.0

### ISSUE THREAD

**Issue by chbdetta** [statelyai/xstate#3010]
### Description

After update to 4.29.0, type check fails:

```
src/index.ts:5:7 - error TS2322: Type 'Timeout' is not assignable to type 'number'.

5 const a: number = setTimeout(() => {}, 0);
        ~

```

Somehow the Node.js types are brought into my project. This was not an issue in 4.28.1

### Expected result

No type error should arise

### Actual result

gets error

### Reproduction

https://github.com/chbdetta/xstate-node-js-type-reproduce
