### ISSUE TITLE
Bug: XState source code can't be typechecked with TS 5.4

### ISSUE THREAD

**Issue by Andarist** [statelyai/xstate#4662]
### XState version

XState version 5

### Description

Our codebase doesn't typecheck with the upcoming TS 5.4 right now

### Expected result

`yarn typecheck` should work

### Actual result

```
packages/core/src/setup.ts:190:5 - error TS2344: Type 'ToStateValue<TConfig>' does not satisfy the constraint 'StateValue'.
  Type 'ToStateValue<MachineConfig<TContext, TEvent, ToProvidedActor<TChildrenMap, TActors, DefaultToUnknownActorLogic<TActors>>, ... 6 more ..., ResolveTypegenMeta<...>>>' is not assignable to type 'StateValue'.
    Type '{} | { [x: string]: {} | { [x: string]: {} | ... | Required<...> | undefined; } | Required<{ [x: string]: {} | ... | Required<...> | undefined; }> | undefined; }' is not assignable to type 'StateValue'.
      Type '{ [x: string]: {} | { [x: string]: {} | ... | Required<...> | undefined; } | Required<{ [x: string]: {} | ... | Required<...> | undefined; }> | undefined; }' is not assignable to type 'StateValue'.

190     ToStateValue<TConfig>,
        ~~~~~~~~~~~~~~~~~~~~~


Found 1 error in packages/core/src/setup.ts:190
```

### Reproduction

yarn typecheck

### Additional context

I bisected this problem to 5.4.0-dev.20231121 and thus to this changeset: https://github.com/microsoft/TypeScript/compare/c10edfbc8dd840c7e5d25b0e2ede2697ef4ac4b6...c266e47794fbd187425989448670238576523d4e

**Comment by rjbrache** [comment]
I'm seeing a similar issue with XState v5.4.1 and the current TS 5.3.3

node_modules/xstate/dist/declarations/src/State.d.ts:5:49 - error TS2344: Type 'NonNullable<TStateValue[K]>' does not satisfy the constraint 'StateValue'.
  Type 'NonNullable<TStateValue[K]>' is not assignable to type 'StateValueMap'.
    Index signature for type 'string' is missing in type '{}'.

5     [K in keyof TStateValue]?: ToTestStateValue<NonNullable<TStateValue[K]>>;

**Comment by Andarist** [comment]
@rjbrache do you have `strictNullChecks` enabled?

**Comment by rjbrache** [comment]
strictNullChecks is not enabled.

**Comment by Andarist** [comment]
That's the problem then - it is required.

**Comment by rjbrache** [comment]
I missed that being a requirement.  Thank you.

**Comment by davidkpiano** [comment]
For more information on TypeScript requirements, see here: https://stately.ai/docs/typescript#set-up-your-tsconfigjson-file

**Comment by Andarist** [comment]
Repro for another problem: [TS playground](https://www.typescriptlang.org/play?noErrorTruncation=true&ts=5.4.0-dev.20240126#code/C4TwDgpgBAkgzgOQgNwgJwDwBUB8UC8UA2lgLpQQAewEAdgCZzG0rrkD8UwaArtAFxQAZgEMANnAgBuAFAzQkKAGEA9gwCWwdWvEAlCAEce6tBHrYANMrX1N22hWp1GUAEYqVYiCNp5CqjS01RxoGJm4+GSgoTn0jEzNsHCioQSxZeXBoAGVgERpsgGMACwgAWxECKABvFLg8mjh2QX1ClTRzerR1WgBzK1z8iCLSipxZAF8Mnpo0UUKchogANXE+AFkRMBqUogBrCBBBLp7e0kFBmlWxPknMxUuVtehCE76oAB8oR+uNrYyFNAAPoAcTQKh4YEeAGlDnAMCksCFnExHiNyiILClssiwlADiAVEIoFgiAAiepDOBk0hYvzfXEuHwgFKcUkUpbU0hEbLkKihFzVLhZQRk4rqertEBkqATFLRThEFioNBWZVseWpEmMphCwGisAiNDiLxiGVy6IK4jZNWsNCkTWiymNGX8lH4w5Eknk50QLk8h2WmLW20qwOWwRKu0DcOCdVoAFZKBgiFQpawkDwpFuvFokoYgY6j2E4ns31c+m1aK0NQAGW8QkEoPBkJhcMsDIAZFA3r0cEQAAykWTRLwiRtQZuptuZjs47u9-sARmHMimckBJJUP2e2CLedGInp2aceKrPc5LQgbQ6GB6QnQ3yszPGa9ZsEQdow2TwOZcEQgTVOGqC0I01IMvhTVt03bLABn7MkxyEGlwMtL4AAp4CQFUMCgtMhgzLN4PJGtaHrccaV-U8XFECRAKDBjLU4AJbCCWg9EMYxTHMVDGKDc8+ME4hoSgHpkxbfCaEIucENI8jkNIUhmi3HcbggBEhM070OSpGkiGhcMtIY18jKDCYsVMy0TwFXVhUgA0jRNCAzVlYMAK1WjJF4vjkiMuM7QAShSQQQMTB5OQCIR1F6Kpz300SHF7c5viWBAVHoCBIuiyZploWZ5kWIY0oyrKYvPQFlLJfIVDKdRChlL4yTaMowAhBgGqgMlDWNMRTQ6skovYlzGvFSU0GlEcLypZTHjgUq7hkDLCjEI1oGWkQ4FRJZNhKHp1KwVS+H3JZfggPBz2QZ40kO6Q30W68VtMYQeFoQo2KgQpTCGHbxRYDA2loeoSVK46ivSzK1Civt0JSAGobSUqsQCi5tpEXa-qwbcTt3LBSpwV8gA)
