### ISSUE TITLE
Bug: getSimplePathPlans() fails with TypeError

### ISSUE THREAD

**Issue by augjoh** [statelyai/xstate#3106]
### Description

After upgrading from 4.30.2 to 4.30.3 `model.getSimplePathPlans()` emits `TypeError`.

### Expected result

Should run as 4.30.2

### Actual result

```
TypeError: (0 , utils_1.keys) is not a function
    at getSimplePaths (/builds/platynum/certification-authority/flows/node_modules/@xstate/graph/lib/graph.js:316:49)
    at TestModel.getSimplePathPlans (/builds/platynum/certification-authority/flows/node_modules/@xstate/test/lib/index.js:157:54)
    at Suite.<anonymous> (/builds/platynum/certification-authority/flows/test/ca-acme.js:989:51)
[...]
```

### Reproduction

https://gitlab.com/platynum/certification-authority/flows/-/blob/master/test/ca-acme.js#L989

### Additional context

[Code that triggers this issue](https://gitlab.com/platynum/certification-authority/flows/-/blob/master/test/ca-acme.js#L989) and [full output](https://gitlab.com/platynum/certification-authority/flows/-/jobs/2156264224#L62) of mocha

**Comment by calvinchengx** [comment]
Yep. Breaks an attempted upgrade to `4.30.2` for me as well.

**Comment by davidkpiano** [comment]
Added a fix in #3113 - sorry about that!
