### ISSUE TITLE
Project using XState fails to build with Typescript 4.5

### ISSUE THREAD

**Issue by HerbCaudill** [statelyai/xstate#2829]
**Description**

TypeScript 4.5 was released 4 days ago (2021-11-17) and it's no longer happy with `/lib/types.d.ts`. This prevents any project that depends on XState from building with the latest version of TypeScript. 

This was picked up by the TypeScript team's bot prior to the release, but they seem to have concluded that this is XState's problem and not theirs. 
https://github.com/microsoft/TypeScript/issues/46610

**Reproduction**

https://github.com/HerbCaudill/xstate-ts45-error-repro

Clone the repo and build. 

**Expected Result**

Build succeeds

**Actual Result**

Build fails: 
```
node_modules/xstate/lib/types.d.ts:90:66 - error TS2344: Type 'TSchema["states"][K]' does not satisfy the constraint 'Required<Pick<StateSchema<any>, "states">>'.
  Type 'TSchema["states"][KeysWithStates<TSchema["states"]>]' is not assignable to type 'Required<Pick<StateSchema<any>, "states">>'.
    Type 'TSchema["states"][{ [K in keyof TSchema["states"]]-?: TSchema["states"][K] extends { states: object; } ? K : never; }[keyof TSchema["states"]]]' is not assignable to type 'Required<Pick<StateSchema<any>, "states">>'.
      Type 'TSchema["states"][TSchema["states"][keyof TSchema["states"]] extends { states: object; } ? keyof TSchema["states"] : never]' is not assignable to type 'Required<Pick<StateSchema<any>, "states">>'.
        Type 'TSchema["states"][keyof TSchema["states"]]' is not assignable to type 'Required<Pick<StateSchema<any>, "states">>'.
          Type 'TSchema["states"][string] | TSchema["states"][number] | TSchema["states"][symbol]' is not assignable to type 'Required<Pick<StateSchema<any>, "states">>'.
            Type 'TSchema["states"][string]' is not assignable to type 'Required<Pick<StateSchema<any>, "states">>'.
              Type 'StateSchema<any>' is not assignable to type 'Required<Pick<StateSchema<any>, "states">>'.
                Property 'states' is optional in type 'StateSchema<any>' but required in type 'Required<Pick<StateSchema<any>, "states">>'.

90     [K in KeysWithStates<TSchema['states']>]?: ExtractStateValue<TSchema['states'][K]>;
                                                                    ~~~~~~~~~~~~~~~~~~~~
```

Note that if you drop the TypeScript version back down to 4.4, the build succeeds.

**Comment by mattpocock** [comment]
We have an open PR introducing it to our repo:

#2828

**Comment by Andarist** [comment]
This should be fixed in [the latest XState releases](https://github.com/statelyai/xstate/releases/tag/xstate%404.26.1). If the issue persists please comment back here and I will reopen this ticket.

**Comment by AliKholmatov** [comment]
![image](https://user-images.githubusercontent.com/87648847/182159556-4540adb0-02d4-470c-9a24-3add57b70581.png)
Hi! In latest versions ExtractStateValue was deleted. What can I use instead of ExtractStateValue? Please)

**Comment by davidkpiano** [comment]
> ![image](https://user-images.githubusercontent.com/87648847/182159556-4540adb0-02d4-470c-9a24-3add57b70581.png) Hi! In latest versions ExtractStateValue was deleted. What can I use instead of ExtractStateValue? Please)

Can you please ask this as a discussion question for tracking purposes? Thank you!
